### ISSUE TITLE
Is there a list of benchmarks provided?

### ISSUE THREAD

**Issue by slerman12** [MushroomRL/mushroom-rl-benchmark#3]
Hi, thanks, this is great. Is there a list of benchmarks provided? Or figures of their performance?

I'm looking to do a full sweep on Atari, MujoCo, and DM-Control. Would the hyperparameters provided here be suitable for all of those? If not, which ones?

**Comment by davide-tateo90** [comment]
We are still finishing the benchmark. When ready, you will find the updated results on the documentation:
https://mushroom-rl-benchmark.readthedocs.io/en/latest/?badge=latest
