### ISSUE TITLE
Is there a way to visualize or track performance during training?

### ISSUE THREAD

**Issue by slerman12** [MushroomRL/mushroom-rl-benchmark#5]

**Comment by davide-tateo90** [comment]
In Mushroom, yes. There is the Plotting callback, see the following example:
https://github.com/MushroomRL/mushroom-rl/blob/dev/examples/plotting_and_normalization.py

In Mushroom  RL benchmark, is not possible, if you exclude sequential/verbose execution, where the performance is shown in the terminal.
Mushroom RL Benchmark is not useful to do RL experiments, it's aim is just to run the benchmark.

**Comment by slerman12** [comment]
Okay, makes sense. But is there an example script for quickly importing predefined hyperparams into the training scripts? And to what extent have you guys tabulated the hyperparams for different algs and envs? That would make it much easier for me to run a full sweep, even without the benchmark data.

**Comment by davide-tateo90** [comment]
As said in #3, the benchmarking process is not complete yet. Probably, we are not going to do a grid search but rely on well-known parameters/parameters from the papers.

Look at the benchmark script, it uses the configuration files inside the cfg folder, which specify the hyperparameters for each algorithm.
