### ISSUE TITLE
errors in benchmark

### ISSUE THREAD

**Issue by davidenitti** [MushroomRL/mushroom-rl-benchmark#7]
I'm trying to run benchmark.py -e BreakoutDeterministic-v4 but I have errors:
```
Traceback (most recent call last):
  File "/home/davide/code/mushroom-rl-benchmark/benchmark.py", line 9, in <module>
    from mushroom_rl_benchmark import BenchmarkSuite
ImportError: cannot import name 'BenchmarkSuite' from 'mushroom_rl_benchmark' (/home/davide/code/mushroom-rl-benchmark/mushroom_rl_benchmark/__init__.py)

```
I managed to fix this changing the import to
`
from mushroom_rl_benchmark.core.suite import BenchmarkSuite
`
but now I have another error:
```
Traceback (most recent call last):
  File "/home/davide/code/mushroom-rl-benchmark/benchmark.py", line 9, in <module>
    from mushroom_rl_benchmark.core.suite import BenchmarkSuite
  File "/home/davide/code/mushroom-rl-benchmark/mushroom_rl_benchmark/core/__init__.py", line 1, in <module>
    from .experiment import BenchmarkExperiment
  File "/home/davide/code/mushroom-rl-benchmark/mushroom_rl_benchmark/core/experiment.py", line 12, in <module>
    from mushroom_rl_benchmark.experiment import exec_run
  File "/home/davide/code/mushroom-rl-benchmark/mushroom_rl_benchmark/experiment/__init__.py", line 1, in <module>
    from .run import exec_run
  File "/home/davide/code/mushroom-rl-benchmark/mushroom_rl_benchmark/experiment/run.py", line 7, in <module>
    from mushroom_rl.utils.dataset import compute_J, parse_dataset, get_init_states
ImportError: cannot import name 'get_init_states' from 'mushroom_rl.utils.dataset' (/home/davide/.local/lib/python3.10/site-packages/mushroom_rl/utils/dataset.py)

```
get_init_states is not defined anywhere

**Comment by davide-tateo90** [comment]
Dear @davidenitti ,
Thanks for letting us know about the issue.
Unfortunately, we have updated mushroom, and we moved some code of the benchmark into the original library (for example, get_initial_states). 
However, we didn't complete the work on the benchmark, as we would like to make a significant refactoring, to get rid of the current Slurm support (which is outdated) and use the experiment_launcher pip package (also maintained by the IAS lab @ TU Darmstadt)

If you want to use the benchmark, you should use the tag [1.1.1](https://github.com/MushroomRL/mushroom-rl-benchmark/releases/tag/1.1.0) and mushroom [1.7.0](https://github.com/MushroomRL/mushroom-rl/releases/tag/1.7.0) (which is a bit outdated, unfortunately)

We don't have time to fix the benchmark right now, but I may take a look at it during the Christmas holidays. Sorry for the problem, and thanks again for reporting!

**Comment by davide-tateo90** [comment]
@davidenitti Good news from the benchmark side! A small Christmas present for all mushroom-rl user base :gift: 

I had time to work on this issue and restructure the benchmark. The code now is much simpler, the logging is fully NumPy, and we should be able to use mushroom-rl 1.9.0


I still need to debug, test some functionality, and clean up the code. Also, we need to release the newest version of mushroom and another software package (experiment launcher)
However, soon we will be able to release the newer benchmark, also easier to maintain (thus, it shouldn't break in the future anymore!)

Merry Christmas from the mushroom-rl team!

**Comment by davidenitti** [comment]
thanks!

**Comment by davidenitti** [comment]
If I import
`from mushroom_rl_benchmark import BenchmarkExperiment`
I have this error now:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'BenchmarkExperiment' from 'mushroom_rl_benchmark' (/home/davide/code/mushroom-rl-benchmark/mushroom_rl_benchmark/__init__.py)

```
maybe the examples need to be updated?

**Comment by davide-tateo90** [comment]
If you are looking at the master branch, is unmantained, currently.

We developed the new version of the benchmark (no example files there) this winter.

Unfortunately due to technical issues with our cluster and lack of time, we still haven't had time to deploy the final version.

We will try to see if we manage to release the new benchmark this summer.

If you find issues in the new version, please let us known. Unfortunately, it has not been tested in depth.
